
markdown: kramdown
highlighter: pygments
paginate: 8
permalink: /:title
gems: [jekyll-paginate]

title: Shihui Guo
url: http://guoshihui.net
feed: /atom.xml
author_info: <a href="http://guoshihui.net/">Shihui Guo</a>
